name: Release
on:
  release:
    types:
      - published

env:
  PYPI_TOKEN: ${{ secrets.URLPATH_PYPI_TOKEN }}
jobs:
  Release:
    runs-on: ubuntu-latest
    container: "python:3.9"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: pip install twine wheel
      - run: python setup.py sdist bdist_wheel
      - run: TWINE_USERNAME=__token__ TWINE_PASSWORD=${PYPI_TOKEN} twine upload dist/*
